// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"playtorium/db"
	"playtorium/handlers"
	"playtorium/services"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, func(), error) {
	gormDB := db.NewPostgresDatabase()
	discountService := services.NewDiscountService(gormDB)
	cartService := services.NewCartService(gormDB, discountService)
	authService := services.NewAuthService(gormDB, cartService)
	authHandler := handlers.NewAuthHandler(authService)
	cartHandler := handlers.NewCartHandler(cartService)
	campaignService := services.NewCampaignService(gormDB)
	campaignHandler := handlers.NewCampaignHandler(campaignService)
	discountHandler := handlers.NewDiscountHandler(discountService)
	discountCategoryService := services.NewDiscountCategoryService(gormDB)
	discountCategoryHandler := handlers.NewDiscountCategoryHandler(discountCategoryService)
	itemService := services.NewItemService(gormDB)
	itemHandler := handlers.NewItemHandler(itemService)
	itemCategoryService := services.NewItemCategoryService(gormDB)
	itemCategoryHandler := handlers.NewItemCategoryHandler(itemCategoryService)
	userService := services.NewUserService(gormDB)
	userHandler := handlers.NewUserHandler(authService, userService)
	engine, err := NewApp(authHandler, cartHandler, campaignHandler, discountHandler, discountCategoryHandler, itemHandler, itemCategoryHandler, userHandler)
	if err != nil {
		return nil, nil, err
	}
	return engine, func() {
	}, nil
}

// wire.go:

var AppSet = wire.NewSet(
	NewApp, db.NewPostgresDatabase,
)

var HandlerSet = wire.NewSet(handlers.NewAuthHandler, handlers.NewCartHandler, handlers.NewCampaignHandler, handlers.NewDiscountHandler, handlers.NewDiscountCategoryHandler, handlers.NewItemHandler, handlers.NewItemCategoryHandler, handlers.NewUserHandler)

var ServiceSet = wire.NewSet(services.NewAuthService, services.NewCartService, services.NewCampaignService, services.NewDiscountService, services.NewDiscountCategoryService, services.NewItemService, services.NewItemCategoryService, services.NewUserService)
