// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"playtorium/db"
	"playtorium/handlers"
	"playtorium/services"
)

// Injectors from wire.go:

func InitializeApp() (*gin.Engine, func(), error) {
	gormDB := db.NewPostgresDatabase()
	discountService := services.NewDiscountService(gormDB)
	cartService := services.NewCartService(gormDB, discountService)
	authService := services.NewAuthService(gormDB, cartService)
	authHandler := handlers.NewAuthHandler(authService)
	cartHandler := handlers.NewCartHandler(cartService)
	cartItemService := services.NewCartItemService(gormDB)
	cartItemHandler := handlers.NewCartItemHandler(cartItemService)
	engine, err := NewApp(authHandler, cartHandler, cartItemHandler)
	if err != nil {
		return nil, nil, err
	}
	return engine, func() {
	}, nil
}

// wire.go:

var AppSet = wire.NewSet(
	NewApp, db.NewPostgresDatabase,
)

var HandlerSet = wire.NewSet(handlers.NewAuthHandler, handlers.NewCartHandler, handlers.NewCartItemHandler)

var ServiceSet = wire.NewSet(services.NewAuthService, services.NewCartService, services.NewCartItemService, services.NewDiscountService)
