CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "username" varchar(255) UNIQUE,
  "password" varchar(255),
  "points" int DEFAULT 0
);

CREATE TABLE "item_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255)
);

CREATE TABLE "items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "price" float,
  "image_name" varchar(255),
  "description" text,
  "item_category_id" int,
  "stock" int
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int,
  "item_id" int,
  "quantity" int,
  "created_at" timestamp DEFAULT (current_timestamp),
  "updated_at" timestamp
);

CREATE TABLE "discount_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE
);

CREATE TABLE "campaigns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE
);

CREATE TABLE "campaign_on_discount_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "campaign_id" int,
  "discount_category_id" int
);

CREATE TABLE "discounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fixed_amount_id" int,
  "percentage_id" int,
  "percentage_category_id" int,
  "seasonal_id" int,
  "point_discount_id" int,
  "discount_category_id" int
);

CREATE TABLE "point_discounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "point" float
);

CREATE TABLE "fixed_amount_discounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "amount" float
);

CREATE TABLE "percentage_discounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "percentage" float
);

CREATE TABLE "percentage_category_discounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "item_category_id" int,
  "percentage" float
);

CREATE TABLE "seasonal_discounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "every_xthb" float,
  "discount_ythb" float
);

ALTER TABLE "items" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("item_id") REFERENCES "items" ("id");

ALTER TABLE "campaign_on_discount_categories" ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "campaign_on_discount_categories" ADD FOREIGN KEY ("discount_category_id") REFERENCES "discount_categories" ("id");

ALTER TABLE "discounts" ADD FOREIGN KEY ("fixed_amount_id") REFERENCES "fixed_amount_discounts" ("id");

ALTER TABLE "discounts" ADD FOREIGN KEY ("percentage_id") REFERENCES "percentage_discounts" ("id");

ALTER TABLE "discounts" ADD FOREIGN KEY ("percentage_category_id") REFERENCES "percentage_category_discounts" ("id");

ALTER TABLE "discounts" ADD FOREIGN KEY ("seasonal_id") REFERENCES "seasonal_discounts" ("id");

ALTER TABLE "discounts" ADD FOREIGN KEY ("point_discount_id") REFERENCES "point_discounts" ("id");

ALTER TABLE "discounts" ADD FOREIGN KEY ("discount_category_id") REFERENCES "discount_categories" ("id");

ALTER TABLE "percentage_category_discounts" ADD FOREIGN KEY ("item_category_id") REFERENCES "item_categories" ("id");
